export const REQUEST_PRODUCTS_INITIAL = 'REQUEST_PRODUCTS_INITIAL'
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS'
export const REQUEST_PRODUCTS_FAIL = 'REQUEST_PRODUCTS_FAIL'

export const REQUEST_PRODUCT_DETAIL_INITIAL = 'REQUEST_PRODUCT_DETAIL_INITIAL'
export const REQUEST_PRODUCT_DETAIL_SUCCESS = 'REQUEST_PRODUCT_DETAIL_SUCCESS'
export const REQUEST_PRODUCT_DETAIL_FAIL = 'REQUEST_PRODUCT_DETAIL_FAIL'