export const REQUEST_LOGIN_INITIAL = 'REQUEST_LOGIN_INITIAL'
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS'
export const REQUEST_LOGIN_FAIL = 'REQUEST_LOGIN_FAIL'
export const REQUEST_LOGIN_LOGOUT = 'REQUEST_LOGIN_LOGOUT'
export const REQUEST_REGISTER_FAIL = 'REQUEST_REGISTER_FAIL'
export const REQUEST_REGISTER_SUCCESS = 'REQUEST_REGISTER_SUCCESS'
export const REQUEST_REGISTER_INITIAL = 'REQUEST_REGISTER_INITIAL'

export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_INITIAL = 'USER_PROFILE_INITIAL'

    

